import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#002b14",
        "primary-container": "#144227",
        "primary-fixed": "#bceec8",
        "primary-fixed-dim": "#a1d2ad",
        "on-primary": "#ffffff",
        "on-primary-container": "#7faf8b",
        "on-primary-fixed": "#00210e",
        "on-primary-fixed-variant": "#234f33",
        secondary: "#795900",
        "secondary-container": "#fed174",
        "secondary-fixed": "#ffdfa0",
        "secondary-fixed-dim": "#ecc165",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785800",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5c4300",
        tertiary: "#451500",
        "tertiary-container": "#652707",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb597",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e78d66",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#753313",
        surface: "#e9ffeb",
        "surface-bright": "#e9ffeb",
        "surface-dim": "#b4e6c0",
        "surface-container": "#c8fad3",
        "surface-container-high": "#c2f4cd",
        "surface-container-highest": "#bceec8",
        "surface-container-low": "#d0ffda",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#3b6849",
        "surface-variant": "#bceec8",
        "on-surface": "#00210e",
        "on-surface-variant": "#414942",
        "on-background": "#00210e",
        background: "#e9ffeb",
        outline: "#717971",
        "outline-variant": "#c1c9c0",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "inverse-surface": "#07381e",
        "inverse-on-surface": "#cafdd6",
        "inverse-primary": "#a1d2ad",
      },
      fontFamily: {
        headline: ["var(--font-epilogue)", "sans-serif"],
        body: ["var(--font-manrope)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.5rem",
        "6xl": "3rem",
      },
    },
  },
  plugins: [],
};
export default config;
